title: "RODINA ROLE PLAY | UNTURNED"
url: "https://executable-rat.github.io"
baseurl: "/rodina-rp-site"

include:
  - _pages
  - _pages/rules
  - _pages/laws
  - _pages/factions

exclude:
  - _pages/_site
  - _posts

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sitemap:
  changefreq: 'weekly'
  priority: 0.8
  
permalink: pretty

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false

sass:
  quiet: true
  sass_dir: _sass
  style: compressed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  
  list_indent: 2
  gfm_quirks: ['paragraph_end']

  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true